Feature/story 22
AllYourGoods/team-do-minor pull request #40
Opened 2024-10-07 09:36 UTC by Edfreded

Added

- Register endpoint
- Login endpoint
- Authorized only endpoint

First create an account (http://localhost:8080/index.html)
![Untitled](https://github.com/user-attachments/assets/e0d15b44-a238-417b-9bc0-d6f929d315b5)

Then login
![login](https://github.com/user-attachments/assets/dad06b6b-4888-4ee7-aa8b-2d546926c930)

add the bearer token to swagger and fetch the test endpoint
![token](https://github.com/user-attachments/assets/12986eb7-ca48-48ac-9b00-90466a21629d)

2024-10-07 12:29 UTC, KiwiLT requested changes
few minor code cleanups, everything worked when testing

2024-10-07 12:29 UTC, KiwiLT commented on Assemblies/AllYourGoods.Api/Data/ApplicationContext.cs
> +    // public override DbSet<User> Users { get; set; } = null!;
old comment

2024-10-07 12:29 UTC, KiwiLT commented on Assemblies/AllYourGoods.Api/Controllers/RestaurantController.cs
> +using Microsoft.AspNetCore.Authorization;
Zijn deze imports nodig in Restaurant controller?

2024-10-07 12:29 UTC, KiwiLT commented on Assemblies/AllYourGoods.Api/Controllers/TestController.cs
Moet weg of moet een test worden

2024-10-07 12:29 UTC, KiwiLT commented on Assemblies/AllYourGoods.Api/Data/ApplicationContext.cs
> +using Microsoft.AspNetCore.Identity;
dubbele import

2024-10-07 12:29 UTC, KiwiLT commented on Assemblies/AllYourGoods.Api/Program.cs
> +        // builder.Services.AddIdentity<User, IdentityRole>()
old comment

2024-10-07 12:29 UTC, KiwiLT commented on Assemblies/AllYourGoods.Api/Program.cs
> +        // Learn more about configuring Swagger/OpenAPI at https://aka.ms/aspnetcore/swashbuckle
weird comment

2024-10-07 12:29 UTC, KiwiLT commented on Assemblies/AllYourGoods.Api/Program.cs
> +        // builder.Services.AddSwaggerGen();
old comment

2024-10-11 13:21 UTC, Edfreded commented
critical changes made. pr obsolete

2024-10-11 13:21 UTC, closed without merging