Feature/story 42
AllYourGoods/team-do-minor pull request #50
Opened 2024-10-14 08:46 UTC by soumaiaMamoo

![DB diagram 12 Okt](https://github.com/user-attachments/assets/0f95d7f3-6ff4-4782-b1ad-0e414bc9ce06)

2024-10-15 08:31 UTC, Jaringvm requested changes

2024-10-15 08:31 UTC, Jaringvm commented on Assemblies/AllYourGoods.Api/Models/Order.cs
> +        public string Note { get; set; }
can be null

2024-10-15 08:31 UTC, Jaringvm commented on Assemblies/AllYourGoods.Api/Models/Order.cs
> +        public double ETA { get; set; }
better to make this a time

2024-10-15 08:31 UTC, Jaringvm commented on Assemblies/AllYourGoods.Api/Models/DeliveryPerson.cs
> +        public TimeSpan EstimatedTime { get; set; }
can be null when the dilvery person is not working yet

2024-10-15 08:31 UTC, Jaringvm commented on Assemblies/AllYourGoods.Api/Models/DeliveryPerson.cs
> +
i think we can remove estimated time because a order already has an estimated time, my bad for overlooking this

2024-10-15 08:31 UTC, Jaringvm commented on Assemblies/AllYourGoods.Api/Models/Roles.cs
> +        public string Id { get; set; }
guid

2024-10-15 08:31 UTC, Jaringvm commented on Assemblies/AllYourGoods.Api/Models/Tag.cs
> +        public string Name { get; set; }
guid

2024-10-15 08:31 UTC, Jaringvm commented on Assemblies/AllYourGoods.Api/Models/User.cs
>      public Role? Role { get; set; }
role can't be null

2024-10-15 08:31 UTC, Jaringvm commented on Assemblies/AllYourGoods.Api/Models/User.cs
>      public string? Name { get; set; }
name can't be null

2024-10-15 08:31 UTC, Jaringvm commented on Assemblies/AllYourGoods.Api/Models/UserRoles.cs
> +
check the feedback of github actions, alot of warnings still occur

2024-10-15 10:37 UTC, fjspaak commented on Assemblies/AllYourGoods.Api/AllYourGoods.Api.csproj
> +    <Folder Include="Migrations\" />
This change is not necessary

2024-10-15 10:37 UTC, fjspaak commented on Assemblies/AllYourGoods.Api/Data/ApplicationContext.cs
> +            modelBuilder.Entity<Restaurant>().ToTable("Restaurant");
A "ToTable" is not needed adding a dbset is enough as done above

2024-10-15 10:37 UTC, fjspaak commented on Assemblies/AllYourGoods.Api/Models/ProductHasTag.cs
> +    public class ProductHasTag
In EFcore we do not need join tables see

https://learn.microsoft.com/en-us/ef/core/modeling/relationships/many-to-many

Giving a product a collection of tags and a tag a collection of products is enough. This makes working with them way easier

2024-10-15 10:37 UTC, fjspaak commented on Assemblies/AllYourGoods.Api/Models/Category.cs
> +        public Guid Id { get; set; }
Every model that ends up as a dbset needs to inherit from BaseEntity and gets it ID from there otherwise generic repositoy wont work

2024-10-17 07:59 UTC, soumaiaMamoo reviewed
Fixed .

2024-10-17 18:41 UTC, Jaringvm approved these changes

2024-10-18 11:02 UTC, fjspaak approved these changes

2024-10-18 11:35 UTC, merged