Feature/story 22
AllYourGoods/team-do-minor pull request #51
Opened 2024-10-14 12:25 UTC by Edfreded

Test endpoints please. restaurant delete endpoint should only be for 'teamhr' members.
also review code regarding readability

2024-10-15 06:50 UTC, MT0993790 approved these changes

2024-10-15 13:17 UTC, KiwiLT requested changes
Maybe someone else should take another look Im not as good with database structure. I dont get the change from 255 to 256 length fields, 255 makes more sense to me. The removal of passwordhash/passwordsalt fields might make sense to rush a testable product? But I thought the dummy fields made more sense as they were before.

2024-10-15 13:17 UTC, KiwiLT commented on Assemblies/AllYourGoods.Api/Controllers/IdentityController.cs
> +            ExpirationDate = DateTime.Now.AddDays(7),
is 7 dagen niet een beetje lang voor refresh token?

2024-10-16 12:51 UTC, Edfreded commented on Assemblies/AllYourGoods.Api/Controllers/IdentityController.cs
> +            ExpirationDate = DateTime.Now.AddDays(7),
7 is standaard voor api's

2024-10-16 12:55 UTC, Edfreded commented on Assemblies/AllYourGoods.Api/Migrations/ApplicationContextModelSnapshot.cs
> +                        .HasColumnType("nvarchar(450)");
Identity _usermanager doet dit zelf

2024-10-16 13:02 UTC, Edfreded commented on Assemblies/AllYourGoods.Api/Controllers/RestaurantController.cs
> +        // [Authorize]
Comment is verwijderd

2024-10-16 13:02 UTC, Edfreded commented on Assemblies/AllYourGoods.Api/Dockerfile.db
> +ENV PATH="$PATH:/opt/mssql-tools/bin"
Comment is verwijderd

2024-10-16 13:07 UTC, Edfreded commented on Assemblies/AllYourGoods.Api/Services/RestaurantService.cs
> +        // }
Dit lijkt de user gekoppeld aan de restaurant te deleten? verduideling zou fijn zijn aangezien dit niet werkt met de nieuwe user tables/ models van microsoft identity. Mocht dit nog nodig zijn kan ik dat implementeren/ fixen als ik weet wat de bedoeling is

2024-10-16 13:15 UTC, Edfreded commented on Assemblies/AllYourGoods.Api/Controllers/IdentityController.cs
> +    [HttpPost("register/pipelinepirates")]
Mogelijk worden rollen verwijderd. feedback volgt

2024-10-16 13:39 UTC, Edfreded commented on Assemblies/AllYourGoods.Api/Controllers/IdentityController.cs
> +    [HttpPost("register/pipelinepirates")]
register endpoints merged. ze zullen een rol moeten opgeven in de POST body. typo is niet mijn problemo

2024-10-27 16:32 UTC, Edfreded commented on Assemblies/AllYourGoods.Api/Services/RestaurantService.cs
> +        // }
Lijkt mij onnodig. aangezien niemand hiervoor iets toe te voegen heeft houd ik het eruit gecomment

2024-10-27 22:35 UTC, KiwiLT approved these changes
I tested the application and scanned the code, it looks good for now. If you arent in a hurry then I want to scan the code tomorrow again, but I think everything should be fine

2024-10-27 22:35 UTC, KiwiLT commented on Assemblies/AllYourGoods.Api/Models/Roles.cs
> +    pipelinepirates
Didnt we make new roles? But dont really mind for now, should be easy to change  into something else later

2024-10-27 22:35 UTC, KiwiLT commented on Assemblies/AllYourGoods.Api/Services/RestaurantService.cs
> +        // }
Maybe its nice to discuss what we are going to do with this

2024-10-29 15:31 UTC, faroeq33 commented on Assemblies/AllYourGoods.Api/Services/RestaurantService.cs
> +        // }
@Edfreded @KiwiLT Kan je dit verwijderen en/of approven en Moesab laten mergen, want onze endpoints zijn afhankelijk van deze feature. Want Order, Restaurant, Menu hebben een ownerid nodig om te kunnen bestaan in de DB)

2024-11-07 17:12 UTC, merged