Feature/initial setup
AllYourGoods/team-do-minor pull request #9
Opened 2024-09-24 20:02 UTC by fjspaak

Initial setup with one Restaurant endpoint example with unit test/ integration test and Docker-compose. All very basic needing to be enhanced still but could do as a starting point

2024-09-26 14:02 UTC, Jaringvm requested changes

2024-09-26 14:05 UTC, Jaringvm commented on Assemblies/AllYourGoods.Api/Models/Restaurant.cs
> +    public Guid Id { get; set; }
Idem

2024-09-26 14:06 UTC, Jaringvm commented on Assemblies/AllYourGoods.Api/Models/Dtos/ViewRestaurantDto.cs
> +    public string? ImageLink { get; set; }
I prefer the more general approach

snake_case for backend & DB
camelCase for frontend and API response

2024-09-26 14:07 UTC, Jaringvm approved these changes

2024-09-26 14:30 UTC, fjspaak commented on Assemblies/AllYourGoods.Api/Models/Dtos/ViewRestaurantDto.cs
> +    public string? ImageLink { get; set; }
c# api database code first naming convention is PascalCase, unlike python where it is snake_case. Since this is a code first database i would recommend sticking to the naming convention. If you download resharper for visual studio it will help with keeping up with naming convention.

https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/coding-style/identifier-names

2024-09-26 14:32 UTC, fjspaak commented on docker-compose.yml
> +      - MSSQL_SA_PASSWORD=DevGeheim01*
This file is for local development only, it will not be part of the release package. Our pipeline should configure this connectionstring for us and indeed possibly store it in an azure keyvault.

2024-09-26 14:36 UTC, fjspaak commented on Tests/AllYourGoods.Api.UnitTests/Services/RestaurantServiceTests.cs
> +            new () { Id = Guid.NewGuid(), Name = "Restaurant 1" },
I personally believe the performance gained from this would be negligible. The advantage of using a Guid vs an int can be significant. There is 0 chance of collisions, we can let the application decide on the ID if neccessary which gives us more room with working with a relational database.  Also for security reasons working with a guid is often recommended since it cant be guessed. We could add a human readable RestaurantNumber if required but i would use Guids as Ids in a code first relational database.

2024-09-26 14:38 UTC, fjspaak commented on Assemblies/AllYourGoods.Api/Migrations/ApplicationContextModelSnapshot.cs
> +                        .HasColumnType("nvarchar(max)");
I dont think we should decide this on our own we do need to get more specific from the other parties what the properties will be and make it as specific as possible in our code

2024-09-26 14:47 UTC, Jaringvm commented on Assemblies/AllYourGoods.Api/Migrations/ApplicationContextModelSnapshot.cs
> +                        .HasColumnType("nvarchar(max)");
Since we're just filling it in temporarily, it makes more sense to set a limit like 255 characters instead of leaving it open with nvarchar(max), so we can keep better control over the data size.

But i agree we should discuss the data sizes with the other teams.

2024-09-26 14:48 UTC, Jaringvm commented on Assemblies/AllYourGoods.Api/Models/Dtos/ViewRestaurantDto.cs
> +    public string? ImageLink { get; set; }
Okay i will use PascalCase for this project, thank you for providing the documentation.

2024-09-26 14:49 UTC, Jaringvm commented on docker-compose.yml
> +      - MSSQL_SA_PASSWORD=DevGeheim01*
Okay great.

2024-09-26 14:54 UTC, Jaringvm commented on Tests/AllYourGoods.Api.UnitTests/Services/RestaurantServiceTests.cs
> +            new () { Id = Guid.NewGuid(), Name = "Restaurant 1" },
I just saw that in the requirements documents of two of the other teams that they are expecting UUID so best option will indeed be to usage GUID's.

2024-09-26 15:03 UTC, MT0993790 requested changes

2024-09-26 15:14 UTC, fjspaak commented on Assemblies/AllYourGoods.Api/Migrations/20240924180753_InitialCreate.cs
> +                });
We need more information about this property and what the requirements are and then update this property

c# entity frameworkcore is a bit more simple we dont create tables we create models and entityframework creates the tables

![image](https://github.com/user-attachments/assets/30891516-87f4-4172-bf65-62d6f13413a4)

We can create a many to many relationship way simpler, i think we should keep everything as simple as possible that we can easily maintain the code

2024-09-26 19:11 UTC, fjspaak commented on Assemblies/AllYourGoods.Api/Migrations/20240924180753_InitialCreate.cs
> +                });
With a new push changed Tag to be a seperate entity with a many to many relationship with Restaurant

2024-09-27 07:04 UTC, MT0993790 approved these changes

2024-09-27 07:05 UTC, MT0993790 commented on Assemblies/AllYourGoods.Api/Migrations/20240924180753_InitialCreate.cs
> +                });
That's good by me

2024-09-27 12:26 UTC, merged